---

- name: Create partition label
  command: parted -s /dev/vdb mklabel gpt
  when: ansible_swaptotal_mb < 1

- name: Create swap partition on local disk
  command: parted /dev/vdb mkpart primary linux-swap 2048s {{swap_size}}
  when: ansible_swaptotal_mb < 1

- name: Create rest partition
  command: parted /dev/vdb mkpart primary zfs {{swap_size}} 100%
  when: ansible_swaptotal_mb < 1

- name: Create swap on local disk
  command: mkswap /dev/vdb1
  when: ansible_swaptotal_mb < 1

- name: Enable swap on local disk
  command: swapon /dev/vdb1
  when: ansible_swaptotal_mb < 1
