---
- name: Install java
  apt: name=default-jdk state=latest

- name: Install pixz
  apt: name=pixz state=latest

- name: Add iRODS apt repository
  apt_repository:
    repo: 'deb https://packages.irods.org/apt/ trusty main'
    state: present

- name: Install iRODS commands
  apt: name=irods-icommands state=latest allow_unauthenticated=yes

- name: Make sure iRODS configuration directory exists
  become: no
  file: path=/home/cloud-user/.irods state=directory

- name: Install iRODS configuration
  become: no
  copy: src=irods_environment.json dest=/home/cloud-user/.irods/irods_environment.json
