---
- name: Clone ECCO Shinyapps public parts from github
  git:
    repo: 'https://github.com/COMHIS/ecco-shinyapps.git'
    dest: /srv/shiny-server/ecco-apps
    version: v1.0

- name: Clone ECCO Shinyapps private data from version.aalto.fi
  git:
    repo: 'git@version.aalto.fi:comhis/data-restricted.git'
    dest: /data/data-restricted
    version: v1.0
    accept_hostkey: yes

- name: Copy data to location accessible to shiny shiny-server
  shell: scp /data/data-restricted/shiny-apps/ecco-estc/data /srv/shiny-server/ecco-apps/data -r

- name: Restart shiny-server
  service: name=shiny-server state=restarted
