---
- name: Add hosts configuration
  template: src=hosts.conf.j2 dest=/etc/hosts

- name: Install Varnish
  apt: name=varnish state=latest
- name: Ensure /etc/systemd/system/varnish.service.d exists
  file: path=/etc/systemd/system/varnish.service.d state=directory
- name: Configure Varnish startup script
  copy: src=varnish-init.conf dest=/etc/systemd/system/varnish.service.d/customexec.conf
- name: Add Varnish configuration
  template: src=varnish.vcl.j2 dest=/etc/varnish/default.vcl
- name: Reload Varnish
  service: name=varnish state=restarted

- name: Install Hitch
  apt: name=hitch state=latest
- name: Add Hitch configuration
  template: src=hitch.conf.j2 dest=/etc/hitch/hitch.conf
- name: Reload Hitch
  service: name=hitch state=restarted

- name: Set Hitch as the service ACME reloads
  copy: src=acme-reload.conf dest=/etc/default/acme-reload
