---
- name: Install R
  apt: name=r-base state=latest

- name: Install R dev for installing packages
  apt: name=r-base-dev state=latest

- name: Install shiny and dependencies in R
  command: /usr/bin/Rscript --slave --no-save --no-restore-history -e "if (! ('{{ item }}' %in% installed.packages()[,'Package'])) { install.packages(pkgs='{{ item }}', repos=c('https://cran.rstudio.com/')); print('Added'); } else { print('Already installed'); }"
  register: r_result
  failed_when: "r_result.rc != 0 or 'had non-zero exit status' in r_result.stderr"
  changed_when: "'Added' in r_result.stdout"
  with_items:
    - shiny
    - rmarkdown

- name: Install shiny-server
  apt: deb=https://download3.rstudio.org/ubuntu-12.04/x86_64/shiny-server-1.5.3.838-amd64.deb

# - name: Copy basic config file for shiny-server
#   copy: src=shiny-server.conf dest=/etc/shiny-server/shiny-server.conf

- name: Install demo shiny apps
  shell: yes | /opt/shiny-server/bin/deploy-example default

- name: Restart shiny-server
  service: name=shiny-server state=restarted
