---
 - name: Attach volume {{volume_name}} to processing-{{name}}
   os_server_volume:
     state: present
     server: processing-{{name}}
     volume: "{{volume_name}}"
   become: no
   delegate_to: localhost

 - wait_for: path=/dev/vdc state=present

 - name: Import zpool {{zpool}}
   command: zpool import {{zpool}} creates=/{{zpool}}

 - name: Unmount dataset {{dataset}}
   command: zfs unmount {{zpool}}/{{dataset}} removes=/{{zpool}}/{{dataset}}

 - name: Import data from {{volume_name}}
   shell: zfs send {{zpool}}/{{dataset}} | zfs receive {{dzpath}} creates=/{{dzpath}}

 - name: Export zpool {{zpool}}
   command: zpool export {{zpool}} removes=/{{zpool}}

 - name: Unattach volume {{volume_name}} from processing-{{name}}
   os_server_volume:
     state: absent
     server: processing-{{name}}
     volume: "{{volume_name}}"
   become: no
   delegate_to: localhost

 - name: Snapshot dataset {{dataset}}
   command: zfs snapshot {{dzpath}}@initial

