heat_template_version: 2015-10-15

description: >
  Build the frontend node and general network environment

resources:

  secgroup_ssh:
    type: OS::Neutron::SecurityGroup
    properties:
      name: public_ssh
      rules:
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 22
          port_range_max: 22
        - protocol: udp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 60000
          port_range_max: 61000


  secgroup_http:
    type: OS::Neutron::SecurityGroup
    properties:
      name: public_http
      rules:
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 80
          port_range_max: 80
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 443
          port_range_max: 443

  public_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: public

  node:
    type: OS::Nova::Server
    properties:
      name: frontend
      flavor: standard.tiny
      image: Ubuntu-16.04
      key_name: comhis
      security_groups:
        - default
        - { get_resource: secgroup_ssh }
        - { get_resource: secgroup_http }
      networks:
        - network: project_2000230

  floating_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: public_ip }
      server_id: { get_resource: node }

outputs:
  node:
    description: The frontend node
    value: { get_attr: [node, show] }
