---
- name: dist-upgrade
  apt: upgrade=dist update_cache=yes
- name: Install mosh
  apt: name=mosh state=latest
- name: Install parallel
  apt: name=parallel state=latest
- name: Install openstack tools
  apt: name=python3-openstackclient state=latest
- name: Install nmon
  apt: name=nmon state=latest
- name: Install htop
  apt: name=htop state=latest
- name: Install atop
  apt: name=atop state=latest
- name: Install whowatch
  apt: name=whowatch state=latest
