---
- name: Set default keyboard language to FI
  copy: src=keyboard.conf dest=/etc/default/keyboard
- name: dist-upgrade
  apt: upgrade=dist update_cache=yes
- name: Install zfs
  apt: name=zfsutils-linux state=latest
- name: Install mosh
  apt: name=mosh state=latest
- name: Install parallel
  apt: name=parallel state=latest
- name: Install openstack tools
  apt: name=python3-openstackclient state=latest
- name: Install common openstack credentials to .profile
  copy: src=profile dest=/home/cloud-user/.profile owner=cloud-user
- name: Install nmon
  apt: name=nmon state=latest
- name: Install htop
  apt: name=htop state=latest
- name: Install atop
  apt: name=atop state=latest
- name: Install iotop
  apt: name=iotop state=latest
- name: Install whowatch
  apt: name=whowatch state=latest
- name: Install fatrace
  apt: name=fatrace state=latest
- name: Install multitail
  apt: name=multitail state=latest
