---
 - name: Attach volume {{volume_name}} to {{name}}
   os_server_volume:
     state: present
     server: "{{name}}"
     volume: "{{volume_name}}"
   become: no
   delegate_to: localhost

 - name: Wait for drive to attach
   wait_for: path=/dev/vdc state=present

 - name: Check if zpool {{zpool}} exists
   stat: path=/{{zpool}}
   register: stat_result

 - name: Import zpool {{zpool}}
   command: zpool import {{zpool}}
   when: stat_result.stat.exists == False

 - name: Remove potential cache drive on {{zpool}}
   command: zpool remove {{zpool}} {{cache_dev}}

 - name: Add cache drive to {{zpool}}
   command: zpool add -f {{zpool}} cache {{cache_dev}}
