---

- include: build-internal.yml name=yle_octavo_api group=octavo-api flavor=io.70GB

- hosts: yle_octavo_api
  become: yes
  roles:
   - common
   - { role: mount-volume-with-cache, name: yle_octavo_api, volume_name: YLEINDEX, zpool: yleindexpool, cache_dev: /dev/vdb }
   - { role: octavo-api, octavo_index_path: /yleindexpool/yleindex, octavo_java_args: -Xmx6G }

- hosts: frontend
  become: yes
  roles:
   - frontend
