---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Build frontend node
      register: build_result
      os_server:
        state: present
        auto_ip: yes
        name: frontend
        meta: group=frontend
        flavor: standard.tiny
        image: Ubuntu-16.04
        key_name: comhis
        security_groups: default, public
        network: project_2000230

- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Add frontend node to inventory
      add_host:
        name: frontend
        groups: frontend
        ansible_ssh_host: "{{ build_result.server.addresses['project_2000230'][1].addr }}"

- include: generate-ssh-config.yml

- hosts: frontend
  gather_facts: no
  tasks:
    - name: Wait for the frontend node to become accessible
      wait_for:
        host: "{{ ansible_ssh_host }}"
        port: 22
        state: started
      delegate_to: localhost

- hosts: frontend
  gather_facts: no
  tasks:
    - name: Add SSH private key to cloud-user
      copy: src=../credentials/comhis.pem dest=/home/cloud-user/.ssh/id_rsa mode=0600
    - name: Add SSH public key to cloud-user
      copy: src=roles/remote-desktop/files/comhis.pub dest=/home/cloud-user/.ssh/id_rsa.pub
    - name: Add SSH private key to root
      copy: src=../credentials/comhis.pem dest=/root/.ssh/id_rsa mode=0600
    - name: Add SSH public key to root
      copy: src=roles/remote-desktop/files/comhis.pub dest=/root/.ssh/id_rsa.pub

- hosts: frontend
  become: yes
  roles:
   - common
   - { role: gronke.dhparam, dhparam_size: 2048, dhparam_file: /var/lib/acme/conf/dhparams }
   - { role: ansible-acmetool, acmetool_responses_method: proxy, acmetool_responses_email: eetu.makela@aalto.fi, acmetool_websrv: varnish, acmetool_responses_install_haproxy_script: "true", acmetool_want: "{{lookup('dig', ansible_ssh_host+'/PTR')[:-1]}}" }
   - frontend
