---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Build internal node {{name}}
      register: build_result
      os_server:
        state: present
        auto_ip: no
        name: "{{name}}"
        meta: group={{group}},groups=internal
        flavor: "{{flavor}}"
        image: Ubuntu-16.04
        key_name: comhis
        security_groups: default
        network: project_2000230

- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Add internal node to inventory
      add_host:
        name: "{{name}}"
        groups: "{{group}},internal"
        ansible_ssh_host: "{{ build_result.server.addresses['project_2000230'][0].addr }}"

- include: generate-ssh-config.yml

- hosts: "{{name}}"
  gather_facts: no
  tasks:
    - name: Wait for the node to become accessible
      wait_for:
        host: "{{ ansible_ssh_host }}"
        port: 22
        state: started
      delegate_to: frontend
