---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Build frontend node
      register: build_result
      os_server:
        state: present
        auto_ip: yes
        name: frontend
        meta: group=frontend
        flavor: standard.tiny
        image: Ubuntu-16.04
        key_name: comhis
        security_groups: default, public
        network: project_2000230

- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Add frontend node to inventory
      add_host:
        name: frontend
        groups: frontend
        ansible_ssh_host: "{{ build_result.server.addresses['project_2000230'][1].addr }}"

- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Generate inventory file
      template: src=templates/node_inventory.j2 dest={{playbook_dir}}/../inventory/nodes

- include: generate-ssh-config.yml

- hosts: frontend
  gather_facts: no
  tasks:
    - name: Wait for the frontend node to become accessible
      wait_for:
        host: "{{ ansible_ssh_host }}"
        port: 22
        state: started
      delegate_to: localhost

- hosts: frontend
  gather_facts: no
  tasks:
    - name: Add SSH private key to node
      copy: src=../../credentials/comhis.pem dest=/home/cloud-user/.ssh/id_rsa mode=0600
    - name: Add SSH public key to node
      copy: src=../../credentials/comhis.pub dest=/home/cloud-user/.ssh/id_rsa.pub

- hosts: frontend
  become: yes
  roles:
   - common
   - frontend
