---

- include: build-internal.yml name=shiny_server group=shiny-server flavor=standard.medium

- hosts: shiny_server
  become: yes
  roles:
   - common
   - shiny-server
   - { role: swap_on_local_disk, swap_size: 20GiB }
   - shiny-app-ecco

- hosts: frontend
  become: yes
  roles:
   - frontend
