---

- include: build-internal.yml name=shiny_server group=shiny-server flavor=standard.medium

- hosts: shiny_server
  become: yes
  roles:
   - common
   - { role: ansible-swapfile, swapfile_size: 10GB, swapfile_swappiness: 10, swapfile_location: /mnt/swapfile }
   - shiny-server
   - shiny-app-ecco

- hosts: frontend
  become: yes
  roles:
   - frontend
