---

- include: build-internal.yml name=eccocluster_octavo_api group=octavo-api flavor=io.70GB

- hosts: eccocluster_octavo_api
  become: yes
  roles:
   - common
   - { role: mount-volume-with-cache, name: eccocluster_octavo_api, volume_name: ECCOCLUSTERINDEX, zpool: eccoclusterindexpool }
   - { role: octavo-api, octavo_index_path: /eccoclusterindexpool/eccoclusterindex, octavo_java_args: -Xmx6G }

- hosts: frontend
  become: yes
  roles:
   - frontend
