---

- include: build-internal.yml name=shiny_server group=shiny-server flavor=standard.medium

- hosts: shiny_server
  become: yes
  roles:
   - common
   - swap_on_file
   - shiny-server
   - shiny-app-ecco

- hosts: frontend
  become: yes
  roles:
   - frontend
